export const LOADING_ITEM_DETAIL: string = "LOADING_ITEM_DETAIL";
export const LOAD_SUCCESS_ITEM_DETAIL: string = "LOAD_SUCCESS_ITEM_DETAIL";
export const LOAD_FAILURE_ITEM_DETAIL: string = "LOAD_FAILURE_ITEM_DETAIL";
export const CLEAN_ITEM_DETAIL: string = "CLEAN_ITEM_DETAIL";